In [4]:
import numpy as np
import torch
import torch.nn as nn
from torch import einsum as ti

In [8]:
torch.manual_seed(31)

In [11]:
x = torch.randn((2,3))
print(x.shape)
x

torch.Size([2, 3])


tensor([[-0.7624,  1.0557, -0.1154],
        [ 0.5772,  0.4651,  0.2977]])

In [12]:
#Permutation of Tensors
#----------------------------------------------#
x_1 = ti("ij->ji", x)
print(x_1.shape)
print(x_1)

torch.Size([3, 2])
tensor([[-0.7624,  0.5772],
        [ 1.0557,  0.4651],
        [-0.1154,  0.2977]])


In [13]:
#Summation

#Summation over all the items
#----------------------------------------------#
x2 = ti("ij->", x)
print(x2)

#Summation over all the columns
#----------------------------------------------#
x3 = ti("ij->j",x)
print(x3)

#Summation over all the Rows
#----------------------------------------------#
x4 = ti("ij->i", x)
print(x4)

tensor(1.5178)
tensor([-0.1852,  1.5208,  0.1823])
tensor([0.1779, 1.3400])


In [15]:
#Matrix-Vector Multiplication
#----------------------------------------------#
# X is of shape [2,3]
v = torch.randn((1, 3))
#Remeber the shape of 'x' is: [2,3], So to multiply [2,3]x[1,3] we need to transpose v, via regular method. Not with EinSUM!
x5 = ti("ij, kj -> ik", x, v)
print(x5.shape)
print(x5)


torch.Size([2, 1])
tensor([[1.7475],
        [2.0190]])


In [17]:
#Matric-Matrix Multiplication
#----------------------------------------------#
x6 = ti("ij,kj->ik", x, x)
print(x6.shape)
print(x6)


torch.Size([2, 2])
tensor([[1.7091, 0.0166],
        [0.0166, 0.6381]])


In [18]:
#Dot Product First row with First row of the Matrix.
#----------------------------------------------#

#This will do dot product and sum it up.
x7 = ti("i,i->", x[0], x[0])
print(x7.shape)
print(x7)

torch.Size([])
tensor(1.7091)


In [19]:
#Dot product with Mmatrix
#----------------------------------------------#

x8 = ti("ij, ij ->", x,x)
print(x8.shape)
print(x8)

torch.Size([])
tensor(2.3471)


In [20]:
#Hadamard Product
#----------------------------------------------#

x9 = ti("ij, ij -> ij", x, x)
print(x9.shape)
print(x9)

torch.Size([2, 3])
tensor([[0.5813, 1.1145, 0.0133],
        [0.3331, 0.2163, 0.0886]])


In [21]:
# Outer Product
#----------------------------------------------#
a = torch.randn((3))
b = torch.randn((5))
print(a,b)
x10 = ti("i,j -> ij", a, b)
print(x10)
print(x10.shape)

tensor([ 0.3011,  0.0309, -0.5694]) tensor([-1.1082,  0.6294,  0.2396,  0.6942,  1.4003])
tensor([[-0.3337,  0.1895,  0.0722,  0.2091,  0.4217],
        [-0.0343,  0.0195,  0.0074,  0.0215,  0.0433],
        [ 0.6310, -0.3584, -0.1365, -0.3953, -0.7974]])
torch.Size([3, 5])


In [23]:
#Batch Matrix Multiplication
#----------------------------------------------#
a = torch.randn((3, 2, 5))
b = torch.randn((3, 5, 3))
x11 = ti("ijk, ikl -> ijl", a, b)
print(x11)
print(x11.shape)

tensor([[[-2.5650, -3.9466,  1.3985],
         [ 0.6729,  0.4678, -1.4392]],

        [[ 1.4161, -2.4872, -1.0086],
         [-2.3177,  4.0892, -0.7044]],

        [[ 3.1235,  0.6923,  2.2228],
         [-0.2678,  1.0338,  0.2762]]])
torch.Size([3, 2, 3])


In [24]:
#Matrix Diagonal
#----------------------------------------------#

x = torch.rand((3,3))
print(x)
x = ti("ii->i", x)
print(x)


tensor([[0.9101, 0.1522, 0.3995],
        [0.8050, 0.3062, 0.1808],
        [0.9059, 0.9003, 0.4182]])
tensor([0.9101, 0.3062, 0.4182])
